# Nav2 Configuration for Bipedal Humanoid Navigation
# Optimized for humanoid-specific footprints and balance requirements

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_assisted_teleop_cancel_bt_node
      - nav2_follow_path_cancel_bt_node
      - nav2_spin_recovery_node_bt_node
      - nav2_wait_recovery_node_bt_node
      - nav2_back_up_recovery_node_bt_node
      - nav2_assisted_teleop_node_bt_node
      - nav2_conrollee_node_bt_node
      - nav2_is_battery_charging_condition_bt_node

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.1
    min_theta_velocity_threshold: 0.01
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # Humanoid-specific progress checker
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 15.0  # Increased for humanoid balance

    # Humanoid-specific goal checker
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25  # Increased for humanoid stepping accuracy
      yaw_goal_tolerance: 0.25
      stateful: true

    # Humanoid-specific path follower
    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      progress_checker_plugin: "progress_checker"
      goal_checker_plugin: "goal_checker"
      # Conservative speeds for humanoid stability
      max_linear_speed: 0.3
      min_linear_speed: 0.05
      max_angular_speed: 0.5
      min_angular_speed: 0.1
      # Balance-aware parameters
      linear_proportional_gain: 2.0
      angular_proportional_gain: 2.0
      balance_margin: 0.15
      step_timing_factor: 1.2

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      resolution: 0.025  # Higher resolution for precise footstep planning
      robot_base_frame: base_link
      transform_tolerance: 0.5
      # Bipedal-specific footprint for humanoid base
      footprint: [[-0.2, -0.15], [-0.2, 0.15], [0.4, 0.15], [0.4, -0.15]]
      plugins: ["voxel_layer", "inflation_layer"]

      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0  # Higher for humanoid safety
        inflation_radius: 0.85    # Larger for balance margin
        robot_radius: 0.45

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: map
      resolution: 0.05
      robot_base_frame: base_link
      transform_tolerance: 0.5
      # Bipedal-specific footprint for humanoid base
      footprint: [[-0.2, -0.15], [-0.2, 0.15], [0.4, 0.15], [0.4, -0.15]]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.1  # Larger for humanoid safety
        robot_radius: 0.5

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: false
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5  # Increased tolerance for humanoid navigation
      use_astar: false
      allow_unknown: true
      # Humanoid-specific parameters
      step_size: 0.5  # Step size for humanoid walking
      min_distance_from_robot: 0.3  # Minimum distance from robot

smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true
      # Humanoid-specific smoothing parameters
      smoothing_weight: 0.05
      curvature_weight: 0.05
      smooth_rate: 20.0

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait", "assisted_teleop"]
    spin:
      plugin: "nav2_behaviors/Spin"
      spin_dist: 1.57  # 90 degrees for humanoid turning
      # Humanoid-specific parameters
      min_duration: 2.0
      max_duration: 10.0
    backup:
      plugin: "nav2_behaviors/BackUp"
      backup_dist: 0.3  # Conservative backup distance for humanoid
      backup_speed: 0.05
      # Humanoid-specific parameters
      min_duration: 1.0
      max_duration: 5.0
    wait:
      plugin: "nav2_behaviors/Wait"
      wait_duration: 5.0
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
      min_vel_theta: 0.1
      # Humanoid-specific parameters
      max_vel_linear: 0.2
      max_vel_theta: 0.3

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 200  # Longer pause for humanoid stability